### ISSUE TITLE
Presets/Schemes

### ISSUE THREAD

**Issue by Galathorne** [FWeynschenk/VideoFilters#3]
Not sure if this is still being watched or developed, but I'm taking a chance here.

I have found your extension to work best out of all the ones I have tried, especially on Netflix. I would not recommend any other as your extension is easy to access and just works when needed. 

I would very much like to be able to get the option to save different presets/schemes/snapshots (basically saved states) of the different values. I am thinking of something in the line of presets you would get in an audio equalizer, but very specifically ones I can save for myself. Different series I follow sometimes always need the same very fine adjustments - some are filmed too dark, not saturated enough, etc. The same goes for some YouTube channels I follow.

Currently I have to adjust the values from a note I made for each and having to reapply them is quite a drag. If there was a way to save states with custom labels for each setting, like the name of the show I am watching, with a dropdown to then choose any of the previously saved profiles, it would be the perfect extension for the task at hand. You could even let us edit the different options in the settings page, even if just to rename or delete unused profiles when done watching some show.

Would love to see this implemented and get an update about the possible progress.

**Comment by FWeynschenk** [comment]
Excellent suggestion! It should be pretty easy to implement, I'll probably get around to it this weekend. Then Google needs to approve the changes which can take a couple of days. It should be updated sometime next week.

No guarantees haha.

**Comment by FWeynschenk** [comment]
@Galathorne I have added the ability to save current settings as a preset; apply a previously saved preset using a dropdown; and deleting a previously created preset.

Now it's waiting for chrome to approve the update and publish it. This can take anything from a day to two months.

**Comment by FWeynschenk** [comment]
@Galathorne Looks like it's live already. Let me know if it doesn't work as you would like.
